# the following block is needed for the shared Docker-based runner
image: docker:git # docker and git clients
variables:
  DOCKER_DRIVER: "overlay" # recommended for docker-in-docker, needs overlay kernel module loaded on host
  TMPDIR: "${CI_PROJECT_DIR}.tmp" # needed for prerelease tests with Gitlab's docker-in-docker
services:
  - docker:dind # enable docker-in-docker

before_script:
  - apk add --update bash coreutils # install industrial_ci dependencies
  # for regular users: - git clone https://github.com/ros-industrial/industrial_ci .ci_config
  - mkdir .ci_config && cp -a * .ci_config # this is only needed for branch testing of industrial_ci itself

indigo:
  script: .ci_config/gitlab.sh
  variables:
    ROS_DISTRO: "indigo"

jade:
  script: .ci_config/gitlab.sh ROS_DISTRO=jade  # alternate syntax

kinetic:
  script: .ci_config/gitlab.sh
  variables:
    ROS_DISTRO: "kinetic"
    PRERELEASE: "true"
