# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)
sudo: required 
dist: trusty 
language: generic 
env:
  - ROS_DISTRO="indigo"
install:
  - git clone --depth 1 https://github.com/ros-industrial/industrial_ci.git .ci_config  
script: 
  - .ci_config/ci.sh
